name: Trigger auto deployment for container-app-ehjoihmggi56g

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-ehjoihmggi56g-AutoDeployTrigger-042bf7f2-ec43-45c8-b569-42e9f7fd264a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPEHJOIHMGGI56G_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPEHJOIHMGGI56G_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPEHJOIHMGGI56G_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPEHJOIHMGGI56G_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPEHJOIHMGGI56G_REGISTRY_PASSWORD }}
          containerAppName: container-app-ehjoihmggi56g
          resourceGroup: todonodejspgsqlgoogleauth8141a44d
          imageToBuild: default/container-app-ehjoihmggi56g:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


